set(need_target 0)
if(NOT "${TARGET}" STREQUAL "")
    message(STATUS "TARGET: ${TARGET} (user-defined)")
elseif(DYNAMIC_ARCH)
    message(STATUS "DYNAMIC_ARCH: ${DYNAMIC_ARCH}")
    set(need_target 1)
elseif(CMAKE_CROSSCOMPILING AND NOT GETARCH_BINARY_DIR)
    set(need_target 1)
else()
    message(STATUS "TARGET: <native> (OpenBLAS getarch/getarch_2nd)")
endif()

if(need_target)
    set(target_default "GENERIC")
    if(MSVC)
        # MSVC does not support the dialect of assembly used in the cpu-specific optimized files
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "^x64|^x86")
        set(target_default "ATOM")
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "^arm64")
        set(target_default "ARMV8")
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "^arm")
        set(target_default "ARMV7")
    endif()
    set(TARGET "${target_default}" CACHE STRING "")
    message(STATUS "TARGET: ${TARGET}")
endif()

if(DEFINED NUM_THREADS)
    message(STATUS "NUM_THREADS: ${NUM_THREADS} (user-defined)")
elseif(EMSCRIPTEN)
    message(STATUS "NUM_THREADS: <default> (for EMSCRIPTEN)")
elseif(need_target)
    set(num_threads_default 24)
    if(ANDROID OR IOS)
        set(num_threads_default 8)
    endif()
    set(NUM_THREADS "${num_threads_default}" CACHE STRING "")
    message(STATUS "NUM_THREADS: ${NUM_THREADS}")
endif()
