"""Majorana-to-Pauli mapping data class for fermion-to-qubit encodings.

This module provides the :class:`MajoranaMapping` data class, which describes
a fermion-to-qubit encoding. The unified primitive across all f2q encodings
is the **bilinear** ``i·gamma_j·gamma_k`` (see :py:meth:`MajoranaMapping.bilinear`):
the parity-even subalgebra of the Majorana Clifford algebra is generated by
these bilinears in every encoding, including redundant encodings (e.g.
Bravyi-Kitaev superfast, Verstraete-Cirac, Derby-Klassen) where individual
Majoranas have no Pauli image.

Standard **Majorana-atomic** encodings (Jordan-Wigner, Bravyi-Kitaev tree,
parity, and their tapered variants) additionally provide a Pauli image for
each individual Majorana operator gamma_k via the ``table`` and
:py:meth:`MajoranaMapping.majorana` interfaces. The factory class methods
on :class:`MajoranaMapping` produce these Majorana-atomic encodings; custom
Majorana-atomic encodings can be constructed from a Pauli table.

References:
    * Chen, Xu, Boettcher, "Equivalence between fermion-to-qubit mappings in
      two spatial dimensions" (2023) — every f2q mapping as a homomorphism
      from the parity-even Majorana Clifford algebra into the Pauli group,
      modulo stabilizers.
    * Jiang, Kalev, Mruczkiewicz, Neven, "Optimal fermion-to-qubit mapping
      via ternary trees..." (2020), and the Majorana loop stabilizer code
      literature.

"""

# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import numpy as np

from qdk_chemistry._core.data import MajoranaMapping as _CoreMajoranaMapping
from qdk_chemistry.data.base import DataClass
from qdk_chemistry.data.tapering import TaperingSpecification

if TYPE_CHECKING:
    import h5py

    from qdk_chemistry.data import Symmetries

__all__: list[str] = []


class MajoranaMapping(DataClass):
    """Immutable data class describing a fermion-to-qubit encoding.

    The unified primitive across all f2q encodings is the **bilinear**
    ``i·gamma_j·gamma_k``, accessible via :py:meth:`bilinear`. Bilinears commute with
    the total fermion parity and with all stabilizers of the codespace, so
    they always have a Pauli image — including in redundant encodings where
    individual Majoranas do not.

    For **Majorana-atomic** encodings (Jordan-Wigner, Bravyi-Kitaev tree,
    parity, and their tapered variants) individual Majoranas gamma_k additionally
    have a Pauli image accessible via :py:meth:`majorana` and the
    ``table`` attribute. Every encoding currently constructible through
    this class is Majorana-atomic; see :py:attr:`is_majorana_atomic`.

    A ``MajoranaMapping`` constructed from a 2N-entry table stores those
    entries as the per-Majorana Pauli image; the bilinear ``i·gamma_j·gamma_k`` is
    computed on demand from the table.

    The mapping is validated at construction time by checking the Clifford
    algebra anticommutation relations: ``{gamma_i, gamma_j} = 2δ_{ij} · I``.
    This guarantees that the mapping defines a valid Majorana-atomic encoding.

    Pauli strings use the same **little-endian** convention as
    :class:`~qdk_chemistry.data.QubitHamiltonian`: qubit 0 is the rightmost
    character.

    Attributes:
        table (tuple[str, ...]): Tuple of 2N dense Pauli strings in little-endian format.
        num_modes (int): Number of fermionic modes (spin-orbitals), N.
        num_qubits (int): Effective number of qubits after any tapering.
        name (str): Human-readable name of the encoding (may be empty for custom mappings).
        is_majorana_atomic (bool): True if individual gamma_k have a Pauli image (always True today).
        stabilizers (tuple[str, ...]): Codespace stabilizer generators (empty for current encodings).
        parity_sector (int): Codespace parity: 0 (unrestricted), +1 (even), -1 (odd). Always 0 today.

    Examples:
        Built-in encodings:

        >>> jw = MajoranaMapping.jordan_wigner(num_modes=4)
        >>> jw.num_modes
        4
        >>> jw.num_qubits
        4

        Custom encoding from Pauli string labels:

        >>> custom = MajoranaMapping(table=["IX", "IY", "XZ", "YZ"], name="my-jw")
        >>> custom.table
        ('IX', 'IY', 'XZ', 'YZ')

        Bilinear lookup:

        >>> coeff, pauli = jw.bilinear(0, 1)

    """

    _data_type_name = "majorana_mapping"
    _serialization_version = "0.1.0"

    def __init__(
        self,
        table: list[str] | tuple[str, ...],
        name: str = "",
        phases: list[int] | tuple[int, ...] | None = None,
        tapering: TaperingSpecification | None = None,
        *,
        _core: _CoreMajoranaMapping | None = None,
    ) -> None:
        """Initialize a MajoranaMapping from a list of dense Pauli-string labels.

        Args:
            table (list[str] | tuple[str, ...]): 2N Pauli strings in little-endian format (qubit 0 = rightmost char).
            name (str): Optional human-readable label for the encoding. Default ``""``.
            phases (list[int] | None): Optional 2N sign factors (+1 or -1) per Majorana operator. Default all +1.
            tapering (TaperingSpecification | None): Optional post-mapping tapering specification.

        Raises:
            ValueError: If the table is invalid (wrong size, bad characters, or Clifford algebra violation).

        """
        if _core is not None:
            self._core = _core
        else:
            self._core = _CoreMajoranaMapping(list(table), name, list(phases) if phases else [])

        # Cache immutable properties from the core
        self._table = self._core.table
        # Allow Python-level name override (e.g. SCBK wraps a BK core)
        self._name = name if name else self._core.name
        self._num_modes = self._core.num_modes
        self._num_qubits = self._core.num_qubits
        self._phases = self._core.phases
        self._tapering = tapering

        # Mark immutable
        super().__init__()

    @property
    def table(self) -> tuple[str, ...]:
        """Tuple of 2N dense Pauli strings in little-endian format (qubit 0 = rightmost char)."""
        return self._table

    @property
    def num_modes(self) -> int:
        """Number of fermionic modes (spin-orbitals)."""
        return self._num_modes

    @property
    def num_qubits(self) -> int:
        """Effective number of qubits after any tapering.

        For untapered encodings this equals the number of qubits in the Pauli
        table.  For tapering-based encodings (e.g. symmetry-conserving
        Bravyi-Kitaev, parity with two-qubit reduction) this reflects the
        reduced qubit count that downstream consumers will see.
        """
        if self._tapering is not None:
            return self._num_qubits - self._tapering.num_tapered
        return self._num_qubits

    @property
    def name(self) -> str:
        """Human-readable name of the encoding (may be empty for custom mappings)."""
        return self._name

    @property
    def phases(self) -> tuple[int, ...]:
        """Tuple of per-entry sign factors (+1 or -1). All +1 for standard encodings."""
        return self._phases

    @property
    def tapering(self) -> TaperingSpecification | None:
        """Post-mapping tapering specification, or None for untapered encodings."""
        return self._tapering

    def without_tapering(self) -> MajoranaMapping:
        """Return a copy of this mapping with tapering stripped.

        The returned mapping has the same Majorana table and phases but
        ``tapering=None`` and ``name`` set to :attr:`base_encoding`.
        This is used by :class:`~qdk_chemistry.algorithms.qubit_mapper.QubitMapper`
        to separate the base encoding from post-mapping tapering.

        Returns:
            A new :class:`MajoranaMapping` with no tapering.

        """
        return MajoranaMapping(table=[], _core=self._core)

    @property
    def base_encoding(self) -> str:
        """The base encoding name used for the Majorana-to-Pauli table.

        For standard encodings this equals :attr:`name`.  For tapering-based
        encodings like symmetry-conserving Bravyi-Kitaev, this returns the
        underlying encoding (e.g. ``"bravyi-kitaev-tree"``) while
        :attr:`name` returns the final encoding label
        (e.g. ``"symmetry-conserving-bravyi-kitaev"``).

        .. important::

           **Plugin dispatch key.**  Name-dispatched
           :class:`~qdk_chemistry.algorithms.QubitMapper` backends
           (OpenFermion, Qiskit) use this property — not :attr:`name` — to
           select the third-party transform function.  Those backends
           ignore :attr:`table` entirely and rebuild the qubit operator
           from scratch.  Consistency between this name and the table
           contents is guaranteed for factory-produced mappings and
           verified by cross-backend tests, but is **not** checked at
           runtime.  See
           :class:`~qdk_chemistry.algorithms.qubit_mapper.QubitMapper`
           for the full dispatch contract.

        """
        return self._core.name

    @property
    def core(self) -> _CoreMajoranaMapping:
        """Access the underlying C++ MajoranaMapping object."""
        return self._core

    @property
    def is_majorana_atomic(self) -> bool:
        """True if individual Majorana operators gamma_k have a Pauli image.

        Always ``True`` for encodings constructible through this class today
        — they are all Majorana-atomic and expose :py:meth:`majorana`.
        Future redundant encodings (e.g. Bravyi-Kitaev superfast,
        Verstraete-Cirac, Derby-Klassen) would return ``False``; for those,
        only :py:meth:`bilinear` is available.
        """
        return bool(self._core.is_majorana_atomic)

    @property
    def stabilizers(self) -> tuple[str, ...]:
        """Stabilizer generators of the codespace.

        Empty for Majorana-atomic encodings (no codespace constraint: the
        full qubit Hilbert space spanned by the Pauli table carries both
        fermion-parity sectors). Reserved for redundant encodings, whose
        codespace is a fixed-parity sector stabilized by
        ``num_qubits - num_modes`` Pauli operators.
        """
        return tuple(self._core.stabilizers)

    @property
    def parity_sector(self) -> int:
        """Parity sector of the codespace.

        - ``0``: unrestricted; the full Fock space spans both parity sectors
          (Majorana-atomic encodings).
        - ``+1``: even-parity codespace.
        - ``-1``: odd-parity codespace.

        Always ``0`` for current encodings.
        """
        return int(self._core.parity_sector)

    def majorana(self, k: int) -> str:
        """Return the Pauli image of the Majorana operator gamma_k.

        Available only for :py:attr:`is_majorana_atomic` encodings (always
        true for current encodings). For tapered encodings the returned
        Pauli string is in the encoding's native (pre-taper) qubit basis,
        i.e. of length ``len(self.table[0])``; tapering, if any, is
        applied downstream by the qubit mapper.

        Args:
            k (int): Majorana index (0 ≤ k < 2 * num_modes).

        Returns:
            str: Dense little-endian Pauli string (qubit 0 = rightmost char).

        Raises:
            IndexError: If k is out of range.

        """
        return self._core.majorana(k)

    def bilinear(self, j: int, k: int) -> tuple[complex, str]:
        """Return the Pauli image of the bilinear ``i·gamma_j·gamma_k``.

        Returns ``(coeff, pauli_str)`` such that the Pauli operator
        ``coeff * pauli_str`` equals ``i·gamma_j·gamma_k`` in the encoded qubit
        representation. Defined for all distinct ``j != k`` in
        ``[0, 2 * num_modes)``.

        For the Majorana-atomic encodings produced by the factory methods
        the returned coefficient is always real (±1), since ``i·gamma_j·gamma_k``
        is Hermitian for ``j != k``. The return type is :class:`complex`
        for generality.

        Bilinears commute with the total fermion parity and with all
        stabilizers of the codespace, so they are the most general
        primitive usable across Majorana-atomic and redundant encodings.

        For tapered encodings the returned Pauli string is in the
        encoding's native (pre-taper) qubit basis, i.e. of length
        ``len(self.table[0])``; tapering, if any, is applied downstream
        by the qubit mapper.

        Args:
            j (int): First Majorana index (0 ≤ j < 2 * num_modes).
            k (int): Second Majorana index (0 ≤ k < 2 * num_modes), must differ from j.

        Returns:
            tuple[complex, str]: ``(coeff, pauli_str)`` in dense little-endian form.

        Raises:
            IndexError: If j or k is out of range.
            ValueError: If j == k.

        """
        return self._core.bilinear(j, k)

    @classmethod
    def jordan_wigner(cls, num_modes: int) -> MajoranaMapping:
        """Construct a Jordan-Wigner encoding.

        Args:
            num_modes (int): Number of fermionic modes (spin-orbitals).

        Returns:
            MajoranaMapping: Mapping with name ``"jordan-wigner"``.

        """
        core = _CoreMajoranaMapping.jordan_wigner(num_modes)
        return cls(table=[], _core=core)

    @classmethod
    def bravyi_kitaev(cls, num_modes: int) -> MajoranaMapping:
        """Construct a Bravyi-Kitaev encoding.

        Args:
            num_modes (int): Number of fermionic modes (spin-orbitals).

        Returns:
            MajoranaMapping: Mapping with name ``"bravyi-kitaev"``.

        """
        core = _CoreMajoranaMapping.bravyi_kitaev(num_modes)
        return cls(table=[], _core=core)

    @classmethod
    def bravyi_kitaev_tree(cls, num_modes: int) -> MajoranaMapping:
        """Construct a balanced binary tree Bravyi-Kitaev encoding.

        Implementation from arXiv:1701.07072 (Havlíček et al.). Unlike the
        Fenwick-tree variant (:meth:`bravyi_kitaev`), the balanced tree has
        guaranteed Z₂ symmetries at qubit positions ``(n/2-1)`` and ``(n-1)``
        for any even ``n``, making it the required base encoding for
        :meth:`symmetry_conserving_bravyi_kitaev` tapering.

        Args:
            num_modes (int): Number of fermionic modes (spin-orbitals).

        Returns:
            MajoranaMapping: Mapping with name ``"bravyi-kitaev-tree"``.

        """
        core = _CoreMajoranaMapping.bravyi_kitaev_tree(num_modes)
        return cls(table=[], _core=core)

    @classmethod
    def parity(
        cls,
        num_modes: int,
        symmetries: Symmetries | None = None,
    ) -> MajoranaMapping:
        """Construct a parity encoding, optionally with two-qubit reduction.

        When ``symmetries`` is provided, the mapping includes a
        :class:`~qdk_chemistry.data.TaperingSpecification` that tapers the two
        Z₂ symmetry qubits (total electron-number parity and alpha-spin
        parity), reducing the qubit count by 2.  This is the same two-qubit
        reduction used by Qiskit Nature's ``ParityMapper(num_particles=...)``.

        Args:
            num_modes (int): Number of fermionic modes (spin-orbitals).
            symmetries (Symmetries | None): If provided, enables two-qubit reduction for the target symmetry sector.

        Returns:
            MajoranaMapping: Mapping with name ``"parity"`` (untapered) or ``"parity-2q-reduced"`` (tapered).

        """
        core = _CoreMajoranaMapping.parity(num_modes)
        if symmetries is not None:
            tapering = TaperingSpecification.parity_two_qubit_reduction(num_modes, symmetries)
            return cls(table=[], name="parity-2q-reduced", tapering=tapering, _core=core)
        return cls(table=[], _core=core)

    @classmethod
    def symmetry_conserving_bravyi_kitaev(
        cls,
        num_modes: int,
        symmetries: Symmetries,
    ) -> MajoranaMapping:
        """Construct a symmetry-conserving Bravyi-Kitaev (SCBK) encoding.

        Combines the balanced binary tree BK mapping
        (:meth:`bravyi_kitaev_tree`) with a
        :class:`~qdk_chemistry.data.TaperingSpecification` that removes the two Z₂
        symmetry qubits (total electron-number parity and alpha-spin parity),
        reducing the qubit count by 2.

        When passed to :meth:`~qdk_chemistry.algorithms.QubitMapper.run`, the
        mapper applies the BK-tree mapping first, then tapers the symmetry
        qubits automatically.

        Args:
            num_modes (int): Number of fermionic modes (spin-orbitals). Must be even and >= 4.
            symmetries (Symmetries): Electron counts for the target symmetry sector.

        Returns:
            MajoranaMapping: BK-tree mapping with SCBK tapering, name ``"symmetry-conserving-bravyi-kitaev"``.

        Raises:
            ValueError: If num_modes < 4 or odd, or electron counts are invalid.

        Examples:
            >>> from qdk_chemistry.data import MajoranaMapping, Symmetries
            >>> mapping = MajoranaMapping.symmetry_conserving_bravyi_kitaev(8, Symmetries(2, 2))
            >>> mapping.name
            'symmetry-conserving-bravyi-kitaev'
            >>> mapping.base_encoding
            'bravyi-kitaev-tree'
            >>> mapping.tapering.num_tapered
            2

        """
        tapering = TaperingSpecification.symmetry_conserving_bravyi_kitaev(num_modes, symmetries)
        core = _CoreMajoranaMapping.bravyi_kitaev_tree(num_modes)
        return cls(
            table=[],
            name="symmetry-conserving-bravyi-kitaev",
            tapering=tapering,
            _core=core,
        )

    @classmethod
    def from_mode_pairs(
        cls,
        pairs: list[tuple[str, str]],
        name: str = "",
    ) -> MajoranaMapping:
        """Construct from (gamma_even, gamma_odd) mode pairs.

        Args:
            pairs (list[tuple[str, str]]): List of (gamma_{2k}, gamma_{2k+1}) Pauli string pairs, one per mode.
            name (str): Optional human-readable label. Default ``""``.

        Returns:
            MajoranaMapping: The constructed mapping.

        Raises:
            ValueError: If pairs are invalid or Clifford algebra validation fails.

        """
        table: list[str] = []
        for even, odd in pairs:
            table.append(even)
            table.append(odd)
        return cls(table=table, name=name)

    @classmethod
    def _from_core(cls, core: _CoreMajoranaMapping) -> MajoranaMapping:
        """Construct from an already-validated C++ core object."""
        return cls(table=[], _core=core)

    def get_summary(self) -> str:
        """Get a human-readable summary of the mapping.

        Returns:
            str: Summary string.

        """
        lines = []
        label = f"MajoranaMapping '{self._name}'" if self._name else "MajoranaMapping (unnamed)"
        lines.append(label)
        lines.append(f"  Modes: {self._num_modes}, Qubits: {self._num_qubits}")
        for k, pauli_str in enumerate(self._table):
            lines.append(f"  gamma_{k} → {pauli_str}")
        return "\n".join(lines)

    def to_json(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dictionary.

        Returns:
            dict[str, Any]: Dictionary representation.

        """
        data: dict[str, Any] = {
            "table": list(self._table),
            "name": self._name,
        }
        # Only include phases if any are non-default (-1)
        if any(p != 1 for p in self._phases):
            data["phases"] = list(self._phases)
        if self._tapering is not None:
            data["tapering"] = self._tapering.to_json()
        return self._add_json_version(data)

    @classmethod
    def from_json(cls, json_data: dict[str, Any]) -> MajoranaMapping:
        """Deserialize from a JSON dictionary.

        Args:
            json_data (dict[str, Any]): Dictionary produced by :meth:`to_json`.

        Returns:
            MajoranaMapping: The deserialized mapping.

        """
        cls._validate_json_version("0.1.0", json_data)
        tapering_data = json_data.get("tapering")
        tapering = TaperingSpecification.from_json(tapering_data) if tapering_data else None
        return cls(
            table=json_data["table"],
            name=json_data.get("name", ""),
            phases=json_data.get("phases"),
            tapering=tapering,
        )

    def to_hdf5(self, group: h5py.Group) -> None:
        """Write to an HDF5 group.

        Args:
            group (h5py.Group): HDF5 group to write to.

        """
        self._add_hdf5_version(group)
        group.attrs["name"] = self._name
        group.attrs["num_modes"] = self._num_modes
        group.create_dataset("table", data=np.array(list(self._table), dtype="S"))
        if any(p != 1 for p in self._phases):
            group.create_dataset("phases", data=np.array(self._phases, dtype=np.int8))
        if self._tapering is not None:
            tg = group.create_group("tapering")
            tg.create_dataset("qubit_indices", data=np.array(self._tapering.qubit_indices, dtype=np.int64))
            tg.create_dataset("eigenvalues", data=np.array(self._tapering.eigenvalues, dtype=np.int8))
            tg.attrs["source_num_qubits"] = self._tapering.source_num_qubits
            tg.attrs["source_encoding"] = self._tapering.source_encoding

    @classmethod
    def from_hdf5(cls, group: h5py.Group) -> MajoranaMapping:
        """Load from an HDF5 group.

        Args:
            group (h5py.Group): HDF5 group to read from.

        Returns:
            MajoranaMapping: The deserialized mapping.

        """
        cls._validate_hdf5_version("0.1.0", group)
        table = [s.decode("utf-8") if isinstance(s, bytes) else s for s in group["table"][()]]
        name = group.attrs.get("name", "")
        if isinstance(name, bytes):
            name = name.decode("utf-8")
        phases = None
        if "phases" in group:
            phases = [int(p) for p in group["phases"][()]]
        tapering = None
        if "tapering" in group:
            tg = group["tapering"]
            src_enc = tg.attrs.get("source_encoding", "")
            if isinstance(src_enc, bytes):
                src_enc = src_enc.decode("utf-8")
            tapering = TaperingSpecification(
                qubit_indices=tuple(int(x) for x in tg["qubit_indices"][()]),
                eigenvalues=tuple(int(x) for x in tg["eigenvalues"][()]),
                source_num_qubits=int(tg.attrs["source_num_qubits"]),
                source_encoding=src_enc,
            )
        return cls(table=table, name=name, phases=phases, tapering=tapering)

    def __repr__(self) -> str:
        """Return a repr string."""
        label = f"'{self._name}', " if self._name else ""
        tapered = f", tapered={self._tapering.num_tapered}" if self._tapering is not None else ""
        return f"MajoranaMapping({label}num_modes={self._num_modes}, num_qubits={self._num_qubits}{tapered})"
