include_guard(GLOBAL)

set(_qdk_unity_default ON)
if(DEFINED CMAKE_UNITY_BUILD)
    set(_qdk_unity_default "${CMAKE_UNITY_BUILD}")
elseif(CMAKE_VERSION VERSION_LESS 3.18)
    set(_qdk_unity_default OFF)
endif()
option(QDK_CHEMISTRY_UNITY_BUILD "Compile compatible QDK sources in unity groups" "${_qdk_unity_default}")
if(QDK_CHEMISTRY_UNITY_BUILD AND CMAKE_VERSION VERSION_LESS 3.18)
    message(FATAL_ERROR "QDK_CHEMISTRY_UNITY_BUILD requires CMake 3.18 or newer")
endif()

function(qdk_unity_group target group)
    set_target_properties(${target} PROPERTIES UNITY_BUILD "${QDK_CHEMISTRY_UNITY_BUILD}")
    if(NOT QDK_CHEMISTRY_UNITY_BUILD)
        return()
    endif()
    set_target_properties(${target} PROPERTIES UNITY_BUILD_MODE GROUP)
    foreach(source IN LISTS ARGN)
        get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        set_source_files_properties("${source}" TARGET_DIRECTORY ${target}
            PROPERTIES UNITY_GROUP "${group}")
    endforeach()
endfunction()
