// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for
// license information.

#pragma once
#include <complex>
#include <cstdint>
#include <qdk/chemistry/data/pauli_operator.hpp>
#include <string>
#include <utility>
#include <vector>

namespace qdk::chemistry::data {

/**
 * @brief Immutable data class describing a fermion-to-qubit encoding.
 *
 * The most general primitive of any fermion-to-qubit encoding is the
 * **bilinear** i·γ_j·γ_k: the parity-even subalgebra of the Majorana
 * Clifford algebra is generated by these bilinears in every encoding,
 * and they always have an explicit Pauli image, even in redundant
 * (stabilizer-code) encodings such as Bravyi-Kitaev superfast where
 * individual Majoranas do not. See ``bilinear()``.
 *
 * For **Majorana-atomic** encodings (Jordan-Wigner, Bravyi-Kitaev tree,
 * parity, and their tapered variants) individual Majorana operators γ_k
 * additionally have a Pauli image, and the encoding can be specified
 * compactly as a 2N-entry table. The current constructors and factory
 * methods of this class all produce Majorana-atomic encodings; the
 * stored ``table`` is the per-Majorana Pauli string. ``majorana()``
 * exposes those entries directly. The bilinear i·γ_j·γ_k is computed on
 * demand from ``i · phases_[j] · phases_[k] · table_[j] · table_[k]``.
 *
 * Future redundant encodings would not have a per-Majorana table; the
 * bilinear API is the unified primitive that covers both regimes.
 *
 * The mapping is validated at construction time by checking the Clifford
 * algebra anticommutation relations: {γ_i, γ_j} = 2δ_{ij} · I. This
 * guarantees that the mapping defines a valid Majorana-atomic encoding.
 *
 * Pauli string convention: The SparsePauliWord entries are stored in the
 * same little-endian convention used by QubitHamiltonian (qubit 0 has the
 * smallest index in the sparse representation).
 *
 * Factory methods construct the standard encodings (Jordan-Wigner,
 * Bravyi-Kitaev, parity) from a mode count. Custom encodings can be
 * constructed directly by providing the table.
 *
 * References:
 *  - Chen, Xu, Boettcher, "Equivalence between fermion-to-qubit mappings
 *    in two spatial dimensions" (2023): every f2q mapping is a
 *    homomorphism from the parity-even Majorana Clifford algebra into
 *    the Pauli group, modulo stabilizers.
 *  - Jiang, Kalev, Mruczkiewicz, Neven, "Optimal fermion-to-qubit
 *    mapping via ternary trees..." (2020) and the Majorana loop
 *    stabilizer code literature: redundant encodings as stabilizer codes.
 *
 * @see PauliTermAccumulator for the accumulation engine that uses this
 * mapping.
 */
class MajoranaMapping {
 public:
  /**
   * @brief Construct a MajoranaMapping from a Majorana-to-Pauli table.
   *
   * @param table Vector of 2N SparsePauliWord entries (one per Majorana
   *              operator gamma_0, gamma_1, ..., gamma_{2N-1}).
   * @param name  Optional human-readable label for the encoding (e.g.,
   *              "jordan-wigner"). Stored but not used for dispatch.
   * @param phases Optional vector of 2N sign factors (+1 or -1) such that
   *               gamma_k = phases[k] * table[k]. If empty, all phases are
   *               assumed +1. Encodings like SCBK produce negative phases.
   * @throws std::invalid_argument If table size is odd, empty, phases size
   *         doesn't match table, phases contain values other than +1/-1,
   *         or the Clifford algebra validation fails.
   */
  explicit MajoranaMapping(std::vector<SparsePauliWord> table,
                           std::string name = "",
                           std::vector<std::int8_t> phases = {});

  /**
   * @brief Number of fermionic modes (spin-orbitals).
   * @return N where the table has 2N entries.
   */
  std::size_t num_modes() const { return table_.size() / 2; }

  /**
   * @brief Number of qubits required by this encoding.
   * @return max qubit index + 1 across all table entries, or 0 if all
   *         entries are identity.
   */
  std::size_t num_qubits() const { return num_qubits_; }

  /**
   * @brief Look up the Pauli string for Majorana operator gamma_k.
   *
   * Returns the unsigned Pauli word table_[k]; the full Majorana operator
   * is gamma_k = phases_[k] * table_[k]. Available only for
   * Majorana-atomic encodings (every encoding constructible today is
   * Majorana-atomic; see ``is_majorana_atomic()``).
   *
   * @param k Majorana index (0 <= k < 2N).
   * @return const reference to the SparsePauliWord for gamma_k.
   * @throws std::out_of_range if k >= 2N.
   */
  const SparsePauliWord& operator()(std::size_t k) const;

  /**
   * @brief Named alias for ``operator()(k)``.
   *
   * Equivalent to ``(*this)(k)``. Provided so call sites that consume
   * the bilinear-first interface can read consistently
   * (``mapping.majorana(k)`` and ``mapping.bilinear(j, k)``).
   *
   * @param k Majorana index (0 <= k < 2N).
   * @return const reference to the SparsePauliWord for gamma_k.
   * @throws std::out_of_range if k >= 2N.
   */
  const SparsePauliWord& majorana(std::size_t k) const { return (*this)(k); }

  /**
   * @brief Pauli image of the bilinear i·γ_j·γ_k.
   *
   * Returns ``(coeff, word)`` such that the Pauli operator
   * ``coeff · word`` equals ``i · γ_j · γ_k`` in the encoded qubit
   * representation. Defined for all distinct ``j != k`` in
   * ``[0, 2 * num_modes())``.
   *
   * For Majorana-atomic encodings this is computed as
   * ``i · phases_[j] · phases_[k] · table_[j] * table_[k]`` using the
   * Pauli algebra. The returned coefficient is always real (±1) for the
   * encodings produced by the factory methods, since ``i·γ_j·γ_k`` is
   * Hermitian; the return type is ``std::complex<double>`` for
   * generality and consistency with
   * ``PauliTermAccumulator::multiply_uncached``.
   *
   * Bilinears commute with the total fermion parity and with all
   * stabilizers of the codespace, so they are the most general primitive
   * usable across Majorana-atomic and redundant encodings alike.
   *
   * For tapered encodings (e.g. SCBK, parity-2q-reduced) this returns
   * the **pre-taper** (source) Pauli string, with qubit indices in
   * ``[0, num_qubits())``. Apply the :class:`TaperingSpecification`
   * separately if you need post-taper coordinates.
   *
   * @param j First Majorana index (0 <= j < 2N).
   * @param k Second Majorana index (0 <= k < 2N), must differ from j.
   * @return pair of (complex coefficient, sparse Pauli word).
   * @throws std::out_of_range if j or k is >= 2N.
   * @throws std::invalid_argument if j == k.
   */
  std::pair<std::complex<double>, SparsePauliWord> bilinear(
      std::size_t j, std::size_t k) const;

  /**
   * @brief Whether the encoding exposes a Pauli image for individual
   *        Majoranas.
   *
   * ``true`` for every encoding currently constructible (the constructor
   * requires a 2N-entry table). Future redundant encodings (Bravyi-
   * Kitaev superfast, Verstraete-Cirac, Derby-Klassen, …) would return
   * ``false``; for those, ``majorana()`` would not be defined and only
   * ``bilinear()`` would be available.
   *
   * @return ``true`` for Majorana-atomic encodings.
   */
  bool is_majorana_atomic() const { return true; }

  /**
   * @brief Stabilizer generators of the codespace.
   *
   * Empty for Majorana-atomic encodings (no codespace constraint: the
   * full 2^num_qubits qubit space carries both fermion-parity sectors).
   * Reserved for redundant encodings whose codespace is a fixed-parity
   * sector stabilized by ``num_qubits - num_modes`` Pauli operators.
   *
   * @return const reference to the stabilizer list (empty for current
   *         encodings).
   */
  const std::vector<SparsePauliWord>& stabilizers() const {
    return stabilizers_;
  }

  /**
   * @brief Parity sector of the encoded codespace.
   *
   * - ``0``: unrestricted; the full Fock space spans both even and odd
   *   parity (Majorana-atomic encodings).
   * - ``+1``: even-parity codespace (typical for redundant encodings on
   *   electron-number-conserving Hamiltonians).
   * - ``-1``: odd-parity codespace (e.g. odd electron count by
   *   construction).
   *
   * Always ``0`` for current encodings.
   */
  int parity_sector() const { return parity_sector_; }

  /**
   * @brief Get the sign factor for Majorana operator gamma_k.
   * @param k Majorana index (0 <= k < 2N).
   * @return +1 or -1.
   */
  std::int8_t phase(std::size_t k) const;

  /**
   * @brief Check if all phases are +1 (fast path for standard encodings).
   * @return true if no entry has a negative phase.
   */
  bool all_phases_positive() const { return all_positive_; }

  /**
   * @brief Access the full Majorana-to-Pauli table.
   * @return const reference to the vector of SparsePauliWords.
   */
  const std::vector<SparsePauliWord>& table() const { return table_; }

  /**
   * @brief Access the phases vector.
   * @return const reference to the vector of sign factors.
   */
  const std::vector<std::int8_t>& phases() const { return phases_; }

  /**
   * @brief Human-readable name of the encoding.
   * @return The name string (may be empty for custom encodings).
   */
  const std::string& name() const { return name_; }

  /**
   * @brief Validate the Clifford algebra anticommutation relations.
   *
   * Checks that {γ_i, γ_j} = φ(γ_i)·φ(γ_j) + φ(γ_j)·φ(γ_i) = 2δ_{ij}·I
   * for all pairs (i, j). This is called automatically at construction.
   *
   * @throws std::invalid_argument if any anticommutator check fails.
   */
  void validate() const;

  // --- Factory methods for standard encodings ---

  /**
   * @brief Construct a Jordan-Wigner encoding.
   *
   * γ_{2j}   = Z_{j-1} ⊗ ... ⊗ Z_0 ⊗ X_j
   * γ_{2j+1} = Z_{j-1} ⊗ ... ⊗ Z_0 ⊗ Y_j
   *
   * @param num_modes Number of fermionic modes (spin-orbitals).
   *                  The encoding uses num_modes qubits.
   * @return MajoranaMapping with name "jordan-wigner".
   */
  static MajoranaMapping jordan_wigner(std::size_t num_modes);

  /**
   * @brief Construct a Bravyi-Kitaev encoding.
   *
   * γ_{2j}   = X_{U(j)} ⊗ X_j ⊗ Z_{P(j)}
   * γ_{2j+1} = X_{U(j)} ⊗ Y_j ⊗ Z_{R(j)}
   *
   * where U(j), P(j), R(j) are the update, parity, and remainder sets
   * derived from the BK binary tree.
   *
   * @param num_modes Number of fermionic modes (spin-orbitals).
   *                  The encoding uses num_modes qubits.
   * @return MajoranaMapping with name "bravyi-kitaev".
   */
  static MajoranaMapping bravyi_kitaev(std::size_t num_modes);

  /**
   * @brief Construct a balanced binary tree Bravyi-Kitaev encoding.
   *
   * Implementation from arXiv:1701.07072 (Havlíček et al.). Unlike the
   * Fenwick-tree BK (``bravyi_kitaev()``), the balanced tree variant has
   * guaranteed Z₂ symmetries at qubit positions (n/2-1) and (n-1) for
   * any even n, making it the required base encoding for
   * symmetry-conserving BK (SCBK) tapering.
   *
   * γ_{2j}   = X_{U(j)} ⊗ X_j ⊗ Z_{P(j)}
   * γ_{2j+1} = X_{U(j)} ⊗ Y_j ⊗ Z_{C(j)}
   *
   * where U(j), P(j) = C(j) ∪ F(j), C(j) are the update, parity,
   * and remainder sets derived from the balanced binary tree.
   *
   * @param num_modes Number of fermionic modes (spin-orbitals).
   *                  The encoding uses num_modes qubits.
   * @return MajoranaMapping with name "bravyi-kitaev-tree".
   */
  static MajoranaMapping bravyi_kitaev_tree(std::size_t num_modes);

  /**
   * @brief Construct a parity encoding.
   *
   * γ_{2j}   = X_{n-1} ⊗ ... ⊗ X_{j+1} ⊗ Y_j ⊗ Z_{j-1} ⊗ ... ⊗ Z_0
   * γ_{2j+1} = X_{n-1} ⊗ ... ⊗ X_{j+1} ⊗ X_j ⊗ Z_{j-1} ⊗ ... ⊗ Z_0
   *
   * @param num_modes Number of fermionic modes (spin-orbitals).
   *                  The encoding uses num_modes qubits.
   * @return MajoranaMapping with name "parity".
   */
  static MajoranaMapping parity(std::size_t num_modes);

 private:
  /// Majorana-to-Pauli table: table_[k] = unsigned Pauli string for gamma_k.
  std::vector<SparsePauliWord> table_;

  /// Per-entry sign factors: gamma_k = phases_[k] * table_[k].
  std::vector<std::int8_t> phases_;

  /// True if all phases are +1 (enables fast-path in engine).
  bool all_positive_;

  /// Human-readable encoding name.
  std::string name_;

  /// Cached qubit count (max qubit index + 1).
  std::size_t num_qubits_;

  /// Stabilizer generators of the codespace. Empty for Majorana-atomic
  /// encodings; reserved for redundant encodings.
  std::vector<SparsePauliWord> stabilizers_{};

  /// Parity sector of the codespace: 0 (unrestricted), +1 (even), or -1
  /// (odd). Always 0 for current encodings.
  int parity_sector_{0};

  /// Compute num_qubits_ from the table.
  static std::size_t compute_num_qubits(
      const std::vector<SparsePauliWord>& table);
};

}  // namespace qdk::chemistry::data
