# Pipeline for building and publishing Python wheels for QDK Chemistry
# Only triggered manually

trigger: none
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: self
    path: qdk-chemistry

parameters:
- name: matrix
  type: object
  default:
  - name: linux_x86_64
    os: linux
    arch: x86_64
    march: x86-64-v3
    imageName: ubuntu-22.04
  - name: linux_aarch64
    os: linux
    arch: aarch64
    march: armv8-a
    imageName: ubuntu-22.04

variables:
- group: QdkChemistry
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      codeql:
        compiled:
          enabled: true
        sourceLanguages: python
        binaryLanguages: cpp
      psscriptanalyzer:
        enabled: false
        justificationForDisabling: Powershell is not used in this repository.
        break: false
      armory:
        enabled: false
        justificationForDisabling: ARM templates are not used in this repository.
        break: false
      eslint:
        enabled: false
        justificationForDisabling: JavaScript is not used in this repository.
        exitOnFatalError: true
      sourceAnalysisPool:
        name: Azure-Pipelines-DevTools-EO
        image: windows-2022
        os: windows
    stages:
    - stage: Build
      displayName: Build C++ Deps and Python Wheels
      jobs:
      - ${{ each target in parameters.matrix }}:
        - job: Build_${{ target.name }}
          ${{ if eq(target.arch, 'aarch64') }}:
            pool:
              name: $(CPU_POOL_ARM)
              demands:
              - ImageOverride -equals ${{ target.imageName }}
              os: ${{ target.os }}
              hostArchitecture: Arm64
          ${{ if eq(target.arch, 'x86_64') }}:
            pool:
              name: $(CPU_POOL_X86)
              demands:
              - ImageOverride -equals ${{ target.imageName }}
              os: ${{ target.os }}
          timeoutInMinutes: 480
          displayName: Build ${{ target.march }} wheels
          variables:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
          strategy:
            matrix:
              Python3.11:
                pythonVersion: '3.11'
                buildMarch: ${{ target.march }}
              Python3.12:
                pythonVersion: '3.12'
                buildMarch: ${{ target.march }}
              Python3.13:
                pythonVersion: '3.13'
                buildMarch: ${{ target.march }}
            maxParallel: 3
          templateContext:
            outputs:
            - output: pipelineArtifact
              displayName: Upload Linux Python $(pythonVersion) Wheels for ${{ target.march }}
              targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse
              artifactName: linux-${{ target.march }}-wheels-python$(pythonVersion)
          steps:
          # Build - x86_64
          - ${{ if eq(target.arch, 'x86_64') }}:
            - template: .pipelines/templates/docker-pip-wheel.yml@self
              parameters:
                march: $(buildMarch)
                buildTesting: OFF
                enableCoverage: OFF
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/amd64
                pythonVersion: $(pythonVersion)

          # Test - x86_64
          - ${{ if eq(target.arch, 'x86_64') }}:
            - template: .pipelines/templates/docker-test-wheel.yml@self
              parameters:
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/amd64
                pythonVersion: $(pythonVersion)

          # Build - ARM64
          - ${{ if eq(target.arch, 'aarch64') }}:
            - template: .pipelines/templates/docker-pip-wheel.yml@self
              parameters:
                march: $(buildMarch)
                buildTesting: OFF
                enableCoverage: OFF
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/arm64/v8
                pythonVersion: $(pythonVersion)

          # Test - ARM64
          - ${{ if eq(target.arch, 'aarch64') }}:
            - template: .pipelines/templates/docker-test-wheel.yml@self
              parameters:
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/arm64/v8
                pythonVersion: $(pythonVersion)

    # - stage: Approval
    #   displayName: Approval
    #   dependsOn: Build
    #   condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    #   jobs:
    #       - job: "Approval"
    #         pool: server
    #         timeoutInMinutes: 1440 # job times out in 1 day
    #         steps:
    #           - task: ManualValidation@0
    #             timeoutInMinutes: 1440 # task times out in 1 day
    #             inputs:
    #               notifyUsers: ""
    #               instructions: "Please verify artifacts and approve the release"
    #               onTimeout: "reject"

    # - stage: release
    #   displayName: Release
    #   dependsOn: approval
    #   condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    #   jobs:
    #     - job: "Publish Python Packages"
    #       pool:
    #         name: "Azure-Pipelines-DevTools-EO"
    #         image: "ubuntu-latest"
    #         os: linux
    #       templateContext:
    #           type: releaseJob
    #           isProduction: true
    #           inputs: # Declare all build artifacts to be consumed in the release job
    #           - input: pipelineArtifact
    #             artifact: linux-x86_64-wheels-python3.11
    #             targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse/linux-x86_64-wheels-python3.11
    #           - input: pipelineArtifact
    #             artifact: linux-x86_64-wheels-python3.12
    #             targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse/linux-x86_64-wheels-python3.12
    #           - input: pipelineArtifact
    #             artifact: linux-x86_64-wheels-python3.13
    #             targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse/linux-x86_64-wheels-python3.13
    #           - input: pipelineArtifact
    #             artifact: linux-aarch64-wheels-python3.11
    #             targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse/linux-aarch64-wheels-python3.11
    #           - input: pipelineArtifact
    #             artifact: linux-aarch64-wheels-python3.12
    #             targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse/linux-aarch64-wheels-python3.12
    #           - input: pipelineArtifact
    #             artifact: linux-aarch64-wheels-python3.13
    #             targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse/linux-aarch64-wheels-python3.13
    #       steps:
    #         - task: EsrpRelease@9
    #           condition: succeeded()
    #           displayName: Publish Python Packages
    #           inputs:
    #             connectedservicename: "PME ESRP Azure Connection"
    #             usemanagedidentity: true
    #             keyvaultname:
    #             signcertname: ESRPCert
    #             clientid:
    #             contenttype: PyPi
    #             domaintenantid:
    #             folderlocation: "$(System.DefaultWorkingDirectory)/qdk-chemistry/python/repaired_wheelhouse"
    #             waitforreleasecompletion: true
    #             owners: "nathanbaker@microsoft.com"
    #             approvers: "nathanbaker@microsoft.com"
    #             mainpublisher: ESRPRELPACMAN
