# Pipeline for building and publishing Python wheels for QDK Chemistry
# Only triggered manually

trigger: none
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: self
    path: qdk-chemistry

parameters:
- name: matrix
  type: object
  default:
  - name: linux_x86_64
    os: linux
    arch: x86_64
    march: x86-64-v3
    imageName: ubuntu-22.04
  - name: linux_aarch64
    os: linux
    arch: aarch64
    march: armv8-a
    imageName: qd-azurelinux3-pt-arm

variables:
- group: QdkChemistry
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-DevTools-EO
        image: windows-2022
        os: windows
    stages:
    - stage: Build
      displayName: Build C++ Deps and Python Wheels
      jobs:
      - ${{ each target in parameters.matrix }}:
        - job: Build_${{ target.name }}
          ${{ if eq(target.arch, 'aarch64') }}:
            pool:
              name: $(CPU_POOL_ARM)
              demands:
              - ImageOverride -equals ${{ target.imageName }}
              os: ${{ target.os }}
              hostArchitecture: Arm64
          ${{ if eq(target.arch, 'x86_64') }}:
            pool:
              name: $(CPU_POOL_X86)
              demands:
              - ImageOverride -equals ${{ target.imageName }}
              os: ${{ target.os }}
          timeoutInMinutes: 480
          displayName: Build ${{ target.march }} wheels
          variables:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
            targetOs: ${{ target.os }}
            targetArch: ${{ target.arch }}
          strategy:
            matrix:
              Python3.11:
                pythonVersion: '3.11'
                buildMarch: ${{ target.march }}
              Python3.12:
                pythonVersion: '3.12'
                buildMarch: ${{ target.march }}
              Python3.13:
                pythonVersion: '3.13'
                buildMarch: ${{ target.march }}
            maxParallel: 1
          templateContext:
            outputs:
            - output: pipelineArtifact
              displayName: Upload Linux Python $(pythonVersion) Wheels for ${{ target.march }}
              targetPath: $(System.DefaultWorkingDirectory)/qdk-chemistry/python/repaired_wheelhouse
              artifactName: linux-${{ target.arch }}-wheels-python$(pythonVersion)
          steps:
          # Build - x86_64
          - ${{ if eq(target.arch, 'x86_64') }}:
            - template: .pipelines/templates/docker-pip-wheel.yml@self
              parameters:
                march: $(buildMarch)
                buildTesting: OFF
                enableCoverage: OFF
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/amd64
                pythonVersion: $(pythonVersion)

          # Test - x86_64
          - ${{ if eq(target.arch, 'x86_64') }}:
            - template: .pipelines/templates/docker-test-wheel.yml@self
              parameters:
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/amd64
                pythonVersion: $(pythonVersion)

          # Build - ARM64
          - ${{ if eq(target.arch, 'aarch64') }}:
            - template: .pipelines/templates/docker-pip-wheel.yml@self
              parameters:
                march: $(buildMarch)
                buildTesting: OFF
                enableCoverage: OFF
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/arm64/v8
                pythonVersion: $(pythonVersion)

          # Test - ARM64
          - ${{ if eq(target.arch, 'aarch64') }}:
            - template: .pipelines/templates/docker-test-wheel.yml@self
              parameters:
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/arm64/v8
                pythonVersion: $(pythonVersion)

          # Deploy: only from main branch and not for PRs
          - task: TwineAuthenticate@1
            displayName: Twine Authenticate for wheel upload
            inputs:
              $(DEPENDENCIES_ARTIFACT_FEED): $(DEPENDENCIES_ARTIFACT_PROJECT)/$(DEPENDENCIES_ARTIFACT_FEED)
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))

          - script: |
              cd $(Agent.BuildDirectory)/qdk-chemistry/python
              pip install --user twine
              python3 -m twine upload -r $(DEPENDENCIES_ARTIFACT_FEED) repaired_wheelhouse/*.whl --config-file $(PYPIRC_PATH)
            displayName: Upload wheel with twine
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))

          # Optional Publish Build Artifacts for debugging before release
          # [GMN] Delete this before release
          # - task: TwineAuthenticate@1
          #   displayName: Twine Authenticate for wheel upload (debug)
          #   inputs:
          #     $(DEPENDENCIES_ARTIFACT_FEED): $(DEPENDENCIES_ARTIFACT_PROJECT)/$(DEPENDENCIES_ARTIFACT_FEED)
          #   condition: and(succeeded(), eq('${{ parameters.forceArtifactUpload }}', 'true'))

          # - script: |
          #     echo "WARNING: Forcing artifact upload. This is intended for debugging purposes only."
          #     cd $(Agent.BuildDirectory)/qdk-chemistry/python
          #     pip install --user twine
          #     python3 -m twine upload -r $(DEPENDENCIES_ARTIFACT_FEED) repaired_wheelhouse/*.whl --config-file $(PYPIRC_PATH)
          #   displayName: Upload wheel with twine (debug)
          #   condition: and(succeeded(), eq('${{ parameters.forceArtifactUpload }}', 'true'))
