# Test the build the wheels on all PRs
# Only deploy to Azure Artifacts on tag push
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - v*
pr:
  branches:
    include:
    - '*'
  drafts: true

parameters:
- name: matrix
  type: object
  default:
  - name: linux_x86_64
    os: linux
    arch: x86_64
    march: x86-64-v3
    imageName: ubuntu-22.04
  - name: linux_aarch64
    os: linux
    arch: aarch64
    march: armv8-a
    imageName: qd-azurelinux3-pt-arm
- name: cpuPoolX86
  displayName: The pool to use for x86_64 CPU builds
  type: string
- name: cpuPoolArm
  displayName: The pool to use for ARM64 CPU builds
  type: string
- name: pcmsolverRef
  displayName: pcmsolver Reference
  default: msft_develop
  type: string
- name: exchCXXRef
  displayName: ExchCXX Reference
  default: msft_develop
  type: string
- name: gauXCRef
  displayName: GauXC Reference
  default: msft_develop
  type: string
- name: forceArtifactUpload
  displayName: Force Artifact Upload
  type: boolean
  default: false
- name: artifactProject
  displayName: Azure DevOps Project ID
  type: string
- name: artifactFeed
  displayName: Azure Artifacts Feed Name
  type: string

resources:
  repositories:
  - repository: self
    path: qdk-chemistry
  - repository: pcmsolver
    type: git
    name: AzureQuantum/pcmsolver
    ref: ${{ parameters.pcmsolverRef }}
  - repository: ExchCXX
    type: git
    name: AzureQuantum/madft-exchcxx
    ref: ${{ parameters.exchCXXRef }}
  - repository: GauXC
    type: git
    name: AzureQuantum/GauXC
    ref: ${{ parameters.gauXCRef }}

stages:
- stage: Build
  displayName: Build C++ Deps and Python Wheels
  jobs:
  - ${{ each target in parameters.matrix }}:
    - job: Build_${{ target.name }}
      ${{ if eq(target.arch, 'aarch64') }}:
        pool:
          name: ${{ parameters.cpuPoolArm }}
          demands:
          - ImageOverride -equals ${{ target.imageName }}
          os: ${{ target.os }}
          hostArchitecture: Arm64
      ${{ if eq(target.arch, 'x86_64') }}:
        pool:
          name: ${{ parameters.cpuPoolX86 }}
          demands:
          - ImageOverride -equals ${{ target.imageName }}
          os: ${{ target.os }}
      timeoutInMinutes: 480
      displayName: Build ${{ target.march }} wheels
      variables:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
        targetOs: ${{ target.os }}
        targetArch: ${{ target.arch }}
      strategy:
        matrix:
          Python3.11:
            pythonVersion: '3.11'
            buildMarch: ${{ target.march }}
          Python3.12:
            pythonVersion: '3.12'
            buildMarch: ${{ target.march }}
          Python3.13:
            pythonVersion: '3.13'
            buildMarch: ${{ target.march }}
          Python3.14:
            pythonVersion: '3.14'
            buildMarch: ${{ target.march }}
        maxParallel: 1 # There are only 2 nodes in the ARM nodepool, limit to 1 job at a time

      steps:
      # Build - x86_64
      - ${{ if eq(target.arch, 'x86_64') }}:
        - template: templates/docker-pip-wheel.yml
          parameters:
            march: $(buildMarch)
            buildTesting: OFF
            enableCoverage: OFF
            agentBuildDirectory: $(Agent.BuildDirectory)
            dockerImage: ubuntu:22.04
            imageTag: linux/amd64
            pythonVersion: $(pythonVersion)

      # Test - x86_64
      - ${{ if eq(target.arch, 'x86_64') }}:
        - template: templates/docker-test-wheel.yml
          parameters:
            agentBuildDirectory: $(Agent.BuildDirectory)
            dockerImage: ubuntu:22.04
            imageTag: linux/amd64
            pythonVersion: $(pythonVersion)

      # Build - ARM64
      - ${{ if eq(target.arch, 'aarch64') }}:
        - template: templates/docker-pip-wheel.yml
          parameters:
            march: $(buildMarch)
            buildTesting: OFF
            enableCoverage: OFF
            agentBuildDirectory: $(Agent.BuildDirectory)
            dockerImage: ubuntu:22.04
            imageTag: linux/arm64/v8
            pythonVersion: $(pythonVersion)

      # Test - ARM64
      - ${{ if eq(target.arch, 'aarch64') }}:
        - template: templates/docker-test-wheel.yml
          parameters:
            agentBuildDirectory: $(Agent.BuildDirectory)
            dockerImage: ubuntu:22.04
            imageTag: linux/arm64/v8
            pythonVersion: $(pythonVersion)

      # Deploy: only from main branch and not for PRs
      - task: TwineAuthenticate@1
        displayName: Twine Authenticate for wheel upload
        inputs:
          artifactFeed: ${{ parameters.artifactProject }}/${{ parameters.artifactFeed }}
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))

      - script: |
          cd $(Agent.BuildDirectory)/qdk-chemistry/python
          pip install --user twine
          python3 -m twine upload -r ${{ parameters.artifactFeed }} repaired_wheelhouse/*.whl --config-file $(PYPIRC_PATH)
        displayName: Upload wheel with twine
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))

      # Optional Publish Build Artifacts for debugging
      - task: TwineAuthenticate@1
        displayName: Twine Authenticate for wheel upload
        inputs:
          artifactFeed: ${{ parameters.artifactProject }}/${{ parameters.artifactFeed }}
        condition: and(succeeded(), eq(${{ parameters.forceArtifactUpload }}, true))

      - script: |
          echo "WARNING: Forcing artifact upload. This is intended for debugging purposes only."
          cd $(Agent.BuildDirectory)/qdk-chemistry/python
          pip install --user twine
          python3 -m twine upload -r ${{ parameters.artifactFeed }} repaired_wheelhouse/*.whl --config-file $(PYPIRC_PATH)
        displayName: Upload wheel with twine
        condition: and(succeeded(), eq(${{ parameters.forceArtifactUpload }}, true))
